/**
 * Slack Integration Service
 * Send notifications and updates to Slack channels
 */

export interface SlackMessage {
  channel: string;
  text: string;
  attachments?: SlackAttachment[];
  blocks?: SlackBlock[];
}

export interface SlackAttachment {
  color?: string;
  title?: string;
  text?: string;
  fields?: { title: string; value: string; short?: boolean }[];
  footer?: string;
  ts?: number;
}

export interface SlackBlock {
  type: string;
  text?: { type: string; text: string };
  elements?: any[];
  fields?: any[];
}

const SLACK_WEBHOOK_URL = import.meta.env.VITE_SLACK_WEBHOOK_URL || '';

/**
 * Send message to Slack channel
 */
export async function sendSlackMessage(message: SlackMessage): Promise<boolean> {
  if (!SLACK_WEBHOOK_URL) {
    console.warn('Slack webhook URL not configured');
    return false;
  }

  try {
    const response = await fetch(SLACK_WEBHOOK_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(message),
    });

    return response.ok;
  } catch (error) {
    console.error('Failed to send Slack message:', error);
    return false;
  }
}

/**
 * Send task notification to Slack
 */
export async function sendTaskNotification(task: {
  title: string;
  assignedTo: string;
  priority: string;
  deadline?: string;
}): Promise<boolean> {
  const priorityColor = {
    low: '#36a64f',
    medium: '#ff9800',
    high: '#f44336',
    urgent: '#9c27b0',
  }[task.priority] || '#808080';

  const message: SlackMessage = {
    channel: '#tasks',
    text: 'New Task Assigned',
    attachments: [
      {
        color: priorityColor,
        title: task.title,
        fields: [
          {
            title: 'Assigned To',
            value: task.assignedTo,
            short: true,
          },
          {
            title: 'Priority',
            value: task.priority.toUpperCase(),
            short: true,
          },
          ...(task.deadline
            ? [
                {
                  title: 'Deadline',
                  value: task.deadline,
                  short: true,
                },
              ]
            : []),
        ],
        footer: 'SaboHub',
        ts: Math.floor(Date.now() / 1000),
      },
    ],
  };

  return sendSlackMessage(message);
}

/**
 * Send attendance alert to Slack
 */
export async function sendAttendanceAlert(alert: {
  employeeName: string;
  type: 'late' | 'absent' | 'early_leave';
  time: string;
}): Promise<boolean> {
  const emoji = {
    late: '⏰',
    absent: '❌',
    early_leave: '🚪',
  }[alert.type];

  const color = {
    late: '#ff9800',
    absent: '#f44336',
    early_leave: '#2196f3',
  }[alert.type];

  const message: SlackMessage = {
    channel: '#attendance',
    text: `${emoji} Attendance Alert`,
    attachments: [
      {
        color,
        title: `${alert.employeeName} - ${alert.type.replace('_', ' ').toUpperCase()}`,
        text: `Time: ${alert.time}`,
        footer: 'SaboHub Attendance System',
        ts: Math.floor(Date.now() / 1000),
      },
    ],
  };

  return sendSlackMessage(message);
}

/**
 * Send KPI alert to Slack
 */
export async function sendKPIAlert(kpi: {
  metric: string;
  currentValue: number;
  threshold: number;
  status: 'warning' | 'critical';
}): Promise<boolean> {
  const color = kpi.status === 'critical' ? '#f44336' : '#ff9800';

  const message: SlackMessage = {
    channel: '#alerts',
    text: '🚨 KPI Alert',
    blocks: [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: '🚨 KPI Alert: Action Required',
        },
      },
      {
        type: 'section',
        fields: [
          {
            type: 'mrkdwn',
            text: `*Metric:*\n${kpi.metric}`,
          },
          {
            type: 'mrkdwn',
            text: `*Status:*\n${kpi.status.toUpperCase()}`,
          },
          {
            type: 'mrkdwn',
            text: `*Current Value:*\n${kpi.currentValue}`,
          },
          {
            type: 'mrkdwn',
            text: `*Threshold:*\n${kpi.threshold}`,
          },
        ],
      },
      {
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: 'Generated by SaboHub Analytics',
          },
        ],
      },
    ],
  };

  return sendSlackMessage(message);
}

/**
 * Send approval request to Slack
 */
export async function sendApprovalRequest(approval: {
  type: string;
  requestedBy: string;
  amount?: string;
  description: string;
  url: string;
}): Promise<boolean> {
  const message: SlackMessage = {
    channel: '#approvals',
    text: 'New Approval Request',
    blocks: [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: '📋 New Approval Request',
        },
      },
      {
        type: 'section',
        fields: [
          {
            type: 'mrkdwn',
            text: `*Type:*\n${approval.type}`,
          },
          {
            type: 'mrkdwn',
            text: `*Requested By:*\n${approval.requestedBy}`,
          },
          ...(approval.amount
            ? [
                {
                  type: 'mrkdwn',
                  text: `*Amount:*\n${approval.amount}`,
                },
              ]
            : []),
        ],
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Description:*\n${approval.description}`,
        },
      },
      {
        type: 'actions',
        elements: [
          {
            type: 'button',
            text: {
              type: 'plain_text',
              text: 'View Details',
            },
            url: approval.url,
            style: 'primary',
          },
        ],
      },
    ],
  };

  return sendSlackMessage(message);
}

/**
 * Send daily summary to Slack
 */
export async function sendDailySummary(summary: {
  date: string;
  tasksCompleted: number;
  attendanceRate: number;
  activeEmployees: number;
  pendingApprovals: number;
}): Promise<boolean> {
  const message: SlackMessage = {
    channel: '#daily-summary',
    text: '📊 Daily Summary',
    blocks: [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: `📊 Daily Summary - ${summary.date}`,
        },
      },
      {
        type: 'section',
        fields: [
          {
            type: 'mrkdwn',
            text: `*Tasks Completed:*\n✅ ${summary.tasksCompleted}`,
          },
          {
            type: 'mrkdwn',
            text: `*Attendance Rate:*\n👥 ${summary.attendanceRate}%`,
          },
          {
            type: 'mrkdwn',
            text: `*Active Employees:*\n💼 ${summary.activeEmployees}`,
          },
          {
            type: 'mrkdwn',
            text: `*Pending Approvals:*\n⏳ ${summary.pendingApprovals}`,
          },
        ],
      },
      {
        type: 'divider',
      },
      {
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: 'Powered by SaboHub Analytics Engine',
          },
        ],
      },
    ],
  };

  return sendSlackMessage(message);
}

/**
 * Test Slack connection
 */
export async function testSlackConnection(): Promise<boolean> {
  const message: SlackMessage = {
    channel: '#general',
    text: '✅ SaboHub integration test successful!',
  };

  return sendSlackMessage(message);
}
