import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Bot, Zap } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export default function CEOAssistant() {
  const navigate = useNavigate();
  const [message, setMessage] = useState('');

  const handleAutoDelegate = () => {
    console.log('🚀 Auto-Delegate triggered!');
    navigate('/ai-task-delegator', { 
      state: { 
        autoGenerated: 'Test task from minimal version',
        timestamp: new Date().toISOString(),
      } 
    });
  };

  // Keyword detection
  const handleSubmit = () => {
    const keywords = ['giao việc', 'giao 10 việc', 'phân công', 'delegate'];
    if (keywords.some(k => message.toLowerCase().includes(k.toLowerCase()))) {
      console.log('🎯 Keyword detected! Auto-delegating...');
      setTimeout(handleAutoDelegate, 1000);
      setMessage('');
      return;
    }
    console.log('💬 Normal message:', message);
    setMessage('');
  };

  return (
    <div className="space-y-6 p-6">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-bold flex items-center gap-3">
          <Bot className="h-8 w-8 text-purple-600" />
          CEO AI Assistant (Minimal Version)
        </h1>
        <Button 
          onClick={handleAutoDelegate}
          className="bg-gradient-to-r from-purple-600 to-blue-600"
        >
          <Zap className="h-4 w-4 mr-2" />
          Auto-Delegate
        </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Test Auto-Delegate</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex gap-2">
            <input
              type="text"
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              onKeyPress={(e) => e.key === 'Enter' && handleSubmit()}
              placeholder="Type: 'Giao 10 việc cấp bách cho manager'"
              className="flex-1 px-3 py-2 border rounded"
            />
            <Button onClick={handleSubmit}>Send</Button>
          </div>
          <div className="text-sm text-muted-foreground">
            Keywords: giao việc, phân công, delegate → Auto-trigger!
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
