import { useState, useEffect, useRef } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useNavigate, useLocation } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Switch } from '@/components/ui/switch';
import { Label } from '@/components/ui/label';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/hooks/use-toast';
import {
  Bot,
  Brain,
  TrendingUp,
  AlertTriangle,
  CheckCircle,
  Send,
  Sparkles,
  Target,
  Users,
  MessageSquare,
  BarChart3,
  Lightbulb,
  Play,
  Settings,
  RefreshCw,
  Zap,
  ListTodo,
  ArrowRight,
} from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { cn } from '@/lib/utils';
import { format } from 'date-fns';
import { vi } from 'date-fns/locale';
import { aiService } from '@/services/aiService';
import type { AIMessage as AIServiceMessage } from '@/services/aiService';

interface AIInsight {
  id: string;
  type: 'opportunity' | 'risk' | 'anomaly' | 'recommendation' | 'prediction';
  priority: 'low' | 'medium' | 'high' | 'critical';
  title: string;
  description: string;
  data: Record<string, any>;
  actions: AIAction[];
  confidence: number;
  createdAt: Date;
  category: string;
}

interface AIAction {
  id: string;
  label: string;
  type: 'create_task' | 'send_alert' | 'approve' | 'schedule_meeting';
  params: Record<string, any>;
}

interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
  insights?: AIInsight[];
}

interface CompanyMetrics {
  employees: { 
    total: number; 
    active: number; 
    onLeave: number;
    workload?: Record<string, { total: number; completed: number; overdue: number }>;
  };
  tasks: { total: number; completed: number; overdue: number; completionRate: number };
  attendance: { avgRate: number; lateCount: number; absentCount: number };
  financial: { revenue: number; expenses: number; profit: number; trend: 'up' | 'down' | 'neutral' };
  kpi: { achieved: number; total: number; percentage: number };
}

/**
 * CEO AI ASSISTANT - JARVIS for Business
 * 
 * Elon Musk Philosophy:
 * - First principles: What does a CEO actually need? Insights, not raw data.
 * - Automation: AI should handle routine analysis, CEO focuses on decisions.
 * - Speed: Real-time insights, not weekly reports.
 * - Proactive: Predict problems, don't just report them.
 */
export default function CEOAssistant() {
  const queryClient = useQueryClient();
  const navigate = useNavigate();
  const location = useLocation();
  const [activeTab, setActiveTab] = useState('assistant');
  const [autoDelegateData, setAutoDelegateData] = useState<{ autoGenerated: string; businessContext: any } | null>(null);
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [inputMessage, setInputMessage] = useState('');
  const [autoAnalysisEnabled, setAutoAnalysisEnabled] = useState(true);
  const [sessionId, setSessionId] = useState<string>(crypto.randomUUID());
  const [isLoadingHistory, setIsLoadingHistory] = useState(true);
  const chatEndRef = useRef<HTMLDivElement>(null);
  
  // Check if coming from auto-delegate redirect
  useEffect(() => {
    if (location.state?.openDelegator) {
      setActiveTab('delegator');
    }
  }, [location.state]);

  // Function to send AI message to Task Delegator
  const handleSendToTaskDelegator = (messageContent: string) => {
    setAutoDelegateData({
      autoGenerated: messageContent,
      businessContext: null,
    });
    setActiveTab('delegator');
  };
  
  // Get AI provider info
  const aiProvider = aiService.getProviderInfo();

  // Fetch real-time company metrics
  const { data: metrics, isLoading: metricsLoading } = useQuery<CompanyMetrics>({
    queryKey: ['ceo-ai-metrics'],
    queryFn: async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const { data: company } = await supabase
        .from('companies')
        .select('id')
        .eq('owner_id', user.id)
        .single();

      if (!company) throw new Error('Company not found');

      // Parallel queries for all metrics (using REAL data + PHASE 3: FINANCIAL!)
      const [employees, tasks, taskAssignments, attendance, financialData] = await Promise.all([
        supabase.from('employees').select('id, full_name, role, is_active, deleted_at').eq('company_id', company.id),
        supabase.from('tasks').select('id, status, due_date, assigned_to, deleted_at').eq('company_id', company.id),
        supabase.from('tasks').select('assigned_to, status').eq('company_id', company.id).not('assigned_to', 'is', null),
        supabase.from('attendance').select('id, user_id, check_in').eq('company_id', company.id).gte('check_in', new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString()),
        supabase.from('financial_transactions').select('type, amount, transaction_date').eq('company_id', company.id).gte('transaction_date', new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString()).is('deleted_at', null),
      ]);

      const activeEmployees = employees.data?.filter(e => e.is_active && !e.deleted_at) || [];
      const activeTasks = tasks.data?.filter(t => !t.deleted_at) || [];
      const completedTasks = activeTasks.filter(t => t.status === 'completed');
      const overdueTasks = activeTasks.filter(t => t.status !== 'completed' && t.due_date && new Date(t.due_date) < new Date());
      
      // NEW: Employee workload analysis
      const workloadByEmployee = taskAssignments.data?.reduce((acc, task) => {
        const empId = task.assigned_to;
        if (!empId) return acc;
        if (!acc[empId]) acc[empId] = { total: 0, completed: 0, overdue: 0 };
        acc[empId].total++;
        if (task.status === 'completed') acc[empId].completed++;
        return acc;
      }, {} as Record<string, {total: number, completed: number, overdue: number}>) || {};

      // Attendance calculation (real data!)
      const totalWorkDays = 22; // ~22 working days in a month
      const attendanceRate = attendance.data && activeEmployees.length > 0
        ? Math.round((attendance.data.length / (activeEmployees.length * totalWorkDays)) * 100)
        : 0;

      // PHASE 3: Financial calculations (90 days)
      const transactions = financialData.data || [];
      const revenue = transactions.filter(t => t.type === 'revenue').reduce((sum, t) => sum + Number(t.amount), 0);
      const expenses = transactions.filter(t => t.type === 'expense').reduce((sum, t) => sum + Number(t.amount), 0);
      const profit = revenue - expenses;
      
      // Calculate trend (last 30 days vs previous 30 days)
      const thirtyDaysAgo = Date.now() - 30 * 24 * 60 * 60 * 1000;
      const sixtyDaysAgo = Date.now() - 60 * 24 * 60 * 60 * 1000;
      const recentRevenue = transactions.filter(t => t.type === 'revenue' && new Date(t.transaction_date).getTime() > thirtyDaysAgo).reduce((sum, t) => sum + Number(t.amount), 0);
      const previousRevenue = transactions.filter(t => t.type === 'revenue' && new Date(t.transaction_date).getTime() > sixtyDaysAgo && new Date(t.transaction_date).getTime() <= thirtyDaysAgo).reduce((sum, t) => sum + Number(t.amount), 0);
      const trend = previousRevenue > 0 ? (recentRevenue > previousRevenue ? 'up' : recentRevenue < previousRevenue ? 'down' : 'neutral') : 'neutral';

      return {
        employees: {
          total: employees.data?.length || 0,
          active: activeEmployees.length,
          onLeave: employees.data?.filter(e => !e.is_active && !e.deleted_at).length || 0,
          workload: workloadByEmployee, // NEW: Workload per employee
        },
        tasks: {
          total: activeTasks.length,
          completed: completedTasks.length,
          overdue: overdueTasks.length,
          completionRate: activeTasks.length > 0 ? Math.round((completedTasks.length / activeTasks.length) * 100) : 0,
        },
        attendance: {
          avgRate: attendanceRate, // REAL data!
          lateCount: 0, // TODO: Parse check_in time
          absentCount: Math.max(0, (activeEmployees.length * totalWorkDays) - (attendance.data?.length || 0)),
        },
        financial: {
          revenue: Math.round(revenue), // PHASE 3: REAL financial data!
          expenses: Math.round(expenses),
          profit: Math.round(profit),
          trend: trend as 'up' | 'down' | 'neutral',
        },
        kpi: {
          achieved: 0, // Phase 2: kpi_actuals table
          total: 0,
          percentage: 0,
        },
      };
    },
    refetchInterval: autoAnalysisEnabled ? 60000 : false, // Refresh every minute if auto-analysis enabled
  });

  // AI-generated insights based on metrics + PREDICTIVE ANALYTICS
  const { data: insights, isLoading: insightsLoading } = useQuery<AIInsight[]>({
    queryKey: ['ceo-ai-insights', metrics],
    queryFn: async () => {
      if (!metrics) return [];

      const generatedInsights: AIInsight[] = [];

      // ============================================
      // PHASE 2: PREDICTIVE ANALYTICS
      // Elon Principle: Predict problems BEFORE they happen
      // ============================================

      // PREDICTION 1: Task Deadline Forecast (7 days ahead)
      const { data: { user } } = await supabase.auth.getUser();
      if (user) {
        const { data: company } = await supabase
          .from('companies')
          .select('id')
          .eq('owner_id', user.id)
          .single();

        if (company) {
          const sevenDaysFromNow = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000);
          const { data: upcomingTasks } = await supabase
            .from('tasks')
            .select('id, due_date, status')
            .eq('company_id', company.id)
            .lte('due_date', sevenDaysFromNow.toISOString())
            .neq('status', 'completed')
            .is('deleted_at', null);

          const criticalUpcoming = upcomingTasks?.filter(t => {
            const daysUntilDue = Math.ceil((new Date(t.due_date).getTime() - Date.now()) / (1000 * 60 * 60 * 24));
            return daysUntilDue <= 3 && daysUntilDue >= 0;
          }) || [];

          if (criticalUpcoming.length > 5) {
            generatedInsights.push({
              id: `insight-${Date.now()}-forecast`,
              type: 'recommendation',
              priority: 'high',
              title: `🔮 Dự báo: ${criticalUpcoming.length} tasks sắp hết hạn trong 3 ngày`,
              description: `AI dự đoán có ${criticalUpcoming.length} nhiệm vụ sẽ đến hạn trong 3 ngày tới. Nên chuẩn bị resources ngay!`,
              data: { upcomingCritical: criticalUpcoming.length, forecast: '3-day window' },
              actions: [
                {
                  id: 'action-forecast',
                  label: 'Xem tasks sắp đến hạn',
                  type: 'create_task',
                  params: { redirect: '/tasks?filter=upcoming' },
                },
                {
                  id: 'action-prep',
                  label: 'Chuẩn bị resources',
                  type: 'create_task',
                  params: { title: 'Prepare team for upcoming deadline rush' },
                },
              ],
              confidence: 0.92,
              createdAt: new Date(),
              category: 'Predictive Analytics',
            });
          }

          // PREDICTION 2: Burnout Risk (based on workload + time)
          if (metrics.employees.workload) {
            const highWorkloadEmployees = Object.entries(metrics.employees.workload)
              .filter(([_, w]) => w.total > 8 && w.completed < w.total * 0.5); // Many tasks, low completion

            if (highWorkloadEmployees.length > 0) {
              generatedInsights.push({
                id: `insight-${Date.now()}-burnout`,
                type: 'risk',
                priority: 'critical',
                title: `🚨 Dự báo: ${highWorkloadEmployees.length} nhân viên có nguy cơ burnout cao`,
                description: `AI phát hiện ${highWorkloadEmployees.length} nhân viên có workload cao (>8 tasks) nhưng tỷ lệ hoàn thành thấp (<50%). Nguy cơ burnout trong 7 ngày!`,
                data: { 
                  atRisk: highWorkloadEmployees.length, 
                  prediction: 'High burnout risk within 7 days',
                  avgWorkload: Math.round(highWorkloadEmployees.reduce((sum, [_, w]) => sum + w.total, 0) / highWorkloadEmployees.length)
                },
                actions: [
                  {
                    id: 'action-burnout-1',
                    label: '🚨 Can thiệp ngay lập tức',
                    type: 'create_task',
                    params: { title: 'Emergency workload redistribution meeting' },
                  },
                  {
                    id: 'action-burnout-2',
                    label: 'Giảm workload',
                    type: 'create_task',
                    params: { title: 'Reduce task load for at-risk employees' },
                  },
                ],
                confidence: 0.88,
                createdAt: new Date(),
                category: 'Predictive Analytics',
              });
            }
          }

          // PREDICTION 3: Attendance Trend (if declining)
          if (metrics.attendance.avgRate < 90 && metrics.attendance.avgRate > 0) {
            const trendPrediction = metrics.attendance.avgRate < 80 ? 'critical decline' : 'concerning trend';
            const projectedRate = Math.max(0, metrics.attendance.avgRate - 5); // Simple linear projection

            generatedInsights.push({
              id: `insight-${Date.now()}-attendance-trend`,
              type: 'anomaly',
              priority: metrics.attendance.avgRate < 80 ? 'critical' : 'high',
              title: `📊 Dự báo: Attendance có thể giảm xuống ${projectedRate}% trong 30 ngày`,
              description: `Dựa trên xu hướng hiện tại (${metrics.attendance.avgRate}%), AI dự đoán tỷ lệ chấm công có thể giảm xuống ${projectedRate}% trong tháng tới nếu không có can thiệp.`,
              data: { 
                currentRate: metrics.attendance.avgRate, 
                projectedRate,
                trend: trendPrediction,
                timeframe: '30 days'
              },
              actions: [
                {
                  id: 'action-attendance-1',
                  label: 'Phân tích nguyên nhân',
                  type: 'create_task',
                  params: { title: 'Analyze root cause of attendance decline' },
                },
                {
                  id: 'action-attendance-2',
                  label: 'Improvement program',
                  type: 'create_task',
                  params: { title: 'Launch attendance improvement initiative' },
                },
              ],
              confidence: 0.75,
              createdAt: new Date(),
              category: 'Predictive Analytics',
            });
          }
        }

        // ==========================================
        // PHASE 3: FINANCIAL INTELLIGENCE
        // ==========================================

        // FINANCIAL INSIGHT 1: Low Profit Margin Warning
        if (metrics.financial.revenue > 0) {
          const profitMargin = (metrics.financial.profit / metrics.financial.revenue) * 100;
          
          if (profitMargin < 30) {
            generatedInsights.push({
              id: `insight-${Date.now()}-financial-margin`,
              type: 'risk',
              priority: profitMargin < 15 ? 'critical' : 'high',
              title: `⚠️ ${profitMargin < 15 ? 'KHẨN CẤP' : 'Cảnh báo'}: Lợi nhuận thấp ${profitMargin.toFixed(1)}%`,
              description: `Tỷ suất lợi nhuận hiện tại chỉ ${profitMargin.toFixed(1)}%, thấp hơn mức an toàn 30%. Doanh thu: ${(metrics.financial.revenue / 1000000).toFixed(0)}M VND, Chi phí: ${(metrics.financial.expenses / 1000000).toFixed(0)}M VND, Lợi nhuận: ${(metrics.financial.profit / 1000000).toFixed(0)}M VND.`,
              data: { 
                profitMargin,
                revenue: metrics.financial.revenue,
                expenses: metrics.financial.expenses,
                profit: metrics.financial.profit,
                threshold: 30
              },
              actions: [
                {
                  id: 'action-financial-1',
                  label: 'Phân tích chi phí',
                  type: 'create_task',
                  params: { title: 'Review and optimize operational expenses' },
                },
                {
                  id: 'action-financial-2',
                  label: 'Tăng doanh thu',
                  type: 'create_task',
                  params: { title: 'Develop revenue growth strategy' },
                },
              ],
              confidence: 0.92,
              createdAt: new Date(),
              category: 'Financial Intelligence',
            });
          }
        }

        // FINANCIAL INSIGHT 2: Revenue Decline Alert
        if (metrics.financial.trend === 'down' && metrics.financial.revenue > 0 && company) {
          // Re-fetch transactions for detailed analysis
          const { data: transactionsData } = await supabase
            .from('financial_transactions')
            .select('type, amount, transaction_date')
            .eq('company_id', company.id)
            .gte('transaction_date', new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString())
            .is('deleted_at', null);
          
          const transactions = transactionsData || [];
          const thirtyDaysAgo = Date.now() - 30 * 24 * 60 * 60 * 1000;
          const sixtyDaysAgo = Date.now() - 60 * 24 * 60 * 60 * 1000;
          
          const recentRevenue = transactions.filter(t => 
            t.type === 'revenue' && new Date(t.transaction_date).getTime() > thirtyDaysAgo
          ).reduce((sum, t) => sum + Number(t.amount), 0);
          
          const previousRevenue = transactions.filter(t => 
            t.type === 'revenue' && 
            new Date(t.transaction_date).getTime() > sixtyDaysAgo &&
            new Date(t.transaction_date).getTime() <= thirtyDaysAgo
          ).reduce((sum, t) => sum + Number(t.amount), 0);
          
          if (previousRevenue > 0) {
            const declinePercent = ((previousRevenue - recentRevenue) / previousRevenue) * 100;
            
            if (declinePercent > 10) {
              generatedInsights.push({
                id: `insight-${Date.now()}-financial-decline`,
                type: 'anomaly',
                priority: declinePercent > 20 ? 'critical' : 'high',
                title: `📉 Cảnh báo: Doanh thu giảm ${declinePercent.toFixed(1)}% trong 30 ngày`,
                description: `Doanh thu tháng gần đây: ${(recentRevenue / 1000000).toFixed(0)}M VND, giảm ${declinePercent.toFixed(1)}% so với tháng trước (${(previousRevenue / 1000000).toFixed(0)}M VND). Cần hành động ngay để đảo ngược xu hướng.`,
                data: { 
                  recentRevenue,
                  previousRevenue,
                  declinePercent,
                  timeframe: '30 days'
                },
                actions: [
                  {
                    id: 'action-revenue-1',
                    label: 'Phân tích nguyên nhân',
                    type: 'create_task',
                    params: { title: 'Analyze revenue decline causes' },
                  },
                  {
                    id: 'action-revenue-2',
                    label: 'Recovery plan',
                    type: 'create_task',
                    params: { title: 'Create revenue recovery action plan' },
                  },
                ],
                confidence: 0.85,
                createdAt: new Date(),
                category: 'Financial Intelligence',
              });
            }
          }
        }

        // FINANCIAL INSIGHT 3: High Expense Ratio Warning
        if (metrics.financial.revenue > 0) {
          const expenseRatio = (metrics.financial.expenses / metrics.financial.revenue) * 100;
          
          if (expenseRatio > 70) {
            generatedInsights.push({
              id: `insight-${Date.now()}-financial-expenses`,
              type: 'risk',
              priority: expenseRatio > 85 ? 'critical' : 'high',
              title: `🚨 Chi phí cao: ${expenseRatio.toFixed(1)}% doanh thu`,
              description: `Chi phí chiếm ${expenseRatio.toFixed(1)}% doanh thu (${(metrics.financial.expenses / 1000000).toFixed(0)}M / ${(metrics.financial.revenue / 1000000).toFixed(0)}M VND). Mức an toàn là dưới 70%. Nguy cơ dòng tiền âm.`,
              data: { 
                expenseRatio,
                expenses: metrics.financial.expenses,
                revenue: metrics.financial.revenue,
                threshold: 70
              },
              actions: [
                {
                  id: 'action-expense-1',
                  label: 'Cost reduction',
                  type: 'create_task',
                  params: { title: 'Identify and implement cost-cutting measures' },
                },
                {
                  id: 'action-expense-2',
                  label: 'Budget review',
                  type: 'create_task',
                  params: { title: 'Review and optimize department budgets' },
                },
              ],
              confidence: 0.88,
              createdAt: new Date(),
              category: 'Financial Intelligence',
            });
          }
        }

        // FINANCIAL PREDICTION 1: Cash Flow Forecast (7-day)
        if (metrics.financial.revenue > 0 && metrics.financial.expenses > 0) {
          // Calculate daily averages
          const daysInData = 90;
          const dailyRevenue = metrics.financial.revenue / daysInData;
          const dailyExpenses = metrics.financial.expenses / daysInData;
          const dailyProfit = dailyRevenue - dailyExpenses;
          
          // Project 7-day cash flow
          const projectedProfit7d = dailyProfit * 7;
          const projectedRevenue7d = dailyRevenue * 7;
          const projectedExpenses7d = dailyExpenses * 7;
          
          generatedInsights.push({
            id: `insight-${Date.now()}-financial-forecast`,
            type: 'prediction',
            priority: projectedProfit7d < 0 ? 'critical' : 'medium',
            title: `📊 Dự báo dòng tiền 7 ngày: ${projectedProfit7d < 0 ? '🚨 ÂM' : '✅ DƯƠNG'} ${(projectedProfit7d / 1000000).toFixed(0)}M VND`,
            description: `Dựa trên 90 ngày dữ liệu, AI dự đoán trong 7 ngày tới: Thu ${(projectedRevenue7d / 1000000).toFixed(0)}M, Chi ${(projectedExpenses7d / 1000000).toFixed(0)}M, Lãi/Lỗ ${(projectedProfit7d / 1000000).toFixed(0)}M VND. Trung bình mỗi ngày: ${(dailyProfit / 1000000).toFixed(1)}M VND.`,
            data: { 
              projectedRevenue7d,
              projectedExpenses7d,
              projectedProfit7d,
              dailyRevenue,
              dailyExpenses,
              dailyProfit,
              timeframe: '7 days'
            },
            actions: projectedProfit7d < 0 ? [
              {
                id: 'action-cashflow-1',
                label: 'Khẩn cấp: Giải pháp dòng tiền',
                type: 'create_task',
                params: { title: 'URGENT: Address negative cash flow projection' },
              },
            ] : [],
            confidence: 0.78,
            createdAt: new Date(),
            category: 'Financial Intelligence',
          });
        }
      }

      // ============================================
      // EXISTING INSIGHTS (Real-time Detection)
      // ============================================

      // Critical: Overdue tasks detection
      if (metrics.tasks.overdue > 5) {
        generatedInsights.push({
          id: `insight-${Date.now()}-1`,
          type: 'risk',
          priority: 'critical',
          title: `⚠️ ${metrics.tasks.overdue} nhiệm vụ quá hạn`,
          description: `Có ${metrics.tasks.overdue} nhiệm vụ đang quá hạn, ảnh hưởng đến tiến độ dự án. Cần can thiệp ngay lập tức.`,
          data: { overdueTasks: metrics.tasks.overdue, totalTasks: metrics.tasks.total },
          actions: [
            {
              id: 'action-1',
              label: 'Xem danh sách nhiệm vụ quá hạn',
              type: 'create_task',
              params: { redirect: '/tasks?filter=overdue' },
            },
            {
              id: 'action-2',
              label: 'Gửi cảnh báo đến managers',
              type: 'send_alert',
              params: { recipients: 'managers', message: 'Critical overdue tasks' },
            },
          ],
          confidence: 0.95,
          createdAt: new Date(),
          category: 'Task Management',
        });
      }

      // Opportunity: High task completion rate
      if (metrics.tasks.completionRate >= 90) {
        generatedInsights.push({
          id: `insight-${Date.now()}-2`,
          type: 'opportunity',
          priority: 'medium',
          title: `🎯 Tỷ lệ hoàn thành nhiệm vụ xuất sắc: ${metrics.tasks.completionRate}%`,
          description: `Team đang có hiệu suất rất tốt. Đây là thời điểm tốt để tăng scope hoặc thưởng cho đội ngũ.`,
          data: { completionRate: metrics.tasks.completionRate },
          actions: [
            {
              id: 'action-3',
              label: 'Tạo chương trình khen thưởng',
              type: 'create_task',
              params: { title: 'Reward high-performing team' },
            },
          ],
          confidence: 0.88,
          createdAt: new Date(),
          category: 'Team Performance',
        });
      }

      // NEW: Employee workload analysis
      if (metrics.employees.workload) {
        const workloadEntries = Object.entries(metrics.employees.workload);
        const overloadedEmployees = workloadEntries.filter(([_, w]) => w.total > 10);
        const underutilizedEmployees = workloadEntries.filter(([_, w]) => w.total < 3);
        
        if (overloadedEmployees.length > 0) {
          generatedInsights.push({
            id: `insight-${Date.now()}-workload`,
            type: 'risk',
            priority: 'high',
            title: `⚠️ ${overloadedEmployees.length} nhân viên quá tải`,
            description: `Có ${overloadedEmployees.length} nhân viên đang xử lý quá nhiều tasks (>10), nguy cơ burnout cao!`,
            data: { overloaded: overloadedEmployees.length },
            actions: [
              {
                id: 'action-workload',
                label: 'Phân phối lại workload',
                type: 'create_task',
                params: { title: 'Redistribute workload to prevent burnout' },
              },
            ],
            confidence: 0.90,
            createdAt: new Date(),
            category: 'Team Capacity',
          });
        }
        
        if (underutilizedEmployees.length > 0) {
          generatedInsights.push({
            id: `insight-${Date.now()}-underutilized`,
            type: 'opportunity',
            priority: 'medium',
            title: `💡 ${underutilizedEmployees.length} nhân viên có capacity`,
            description: `Có ${underutilizedEmployees.length} nhân viên đang có ít tasks (<3), có thể assign thêm việc.`,
            data: { underutilized: underutilizedEmployees.length },
            actions: [
              {
                id: 'action-assign',
                label: 'Assign thêm tasks',
                type: 'create_task',
                params: { title: 'Assign tasks to available team members' },
              },
            ],
            confidence: 0.85,
            createdAt: new Date(),
            category: 'Team Capacity',
          });
        }
      }

      // Anomaly: Low attendance rate
      if (metrics.attendance.avgRate < 85 && metrics.attendance.avgRate > 0) {
        generatedInsights.push({
          id: `insight-${Date.now()}-3`,
          type: 'anomaly',
          priority: 'high',
          title: `📉 Tỷ lệ chấm công thấp: ${metrics.attendance.avgRate}%`,
          description: `Tỷ lệ chấm công đang thấp hơn mức chuẩn (90%). Có thể có vấn đề về morale hoặc hệ thống.`,
          data: { avgRate: metrics.attendance.avgRate, absentCount: metrics.attendance.absentCount },
          actions: [
            {
              id: 'action-4',
              label: 'Kiểm tra nguyên nhân',
              type: 'create_task',
              params: { title: 'Investigate attendance issues' },
            },
            {
              id: 'action-5',
              label: 'Họp với HR',
              type: 'schedule_meeting',
              params: { topic: 'Attendance concerns' },
            },
          ],
          confidence: 0.82,
          createdAt: new Date(),
          category: 'Attendance',
        });
      }

      // Recommendation: KPI tracking
      if (metrics.kpi.percentage < 70 && metrics.kpi.total > 0) {
        generatedInsights.push({
          id: `insight-${Date.now()}-4`,
          type: 'recommendation',
          priority: 'high',
          title: `🎯 Chỉ ${metrics.kpi.percentage}% KPI đạt mục tiêu`,
          description: `Nhiều KPI đang không đạt target. Cần review và điều chỉnh chiến lược hoặc mục tiêu.`,
          data: { achieved: metrics.kpi.achieved, total: metrics.kpi.total },
          actions: [
            {
              id: 'action-6',
              label: 'Review KPI targets',
              type: 'create_task',
              params: { title: 'Review and adjust KPI targets' },
            },
            {
              id: 'action-7',
              label: 'Họp strategic planning',
              type: 'schedule_meeting',
              params: { topic: 'KPI review meeting' },
            },
          ],
          confidence: 0.91,
          createdAt: new Date(),
          category: 'Strategic Planning',
        });
      }

      return generatedInsights;
    },
    enabled: !!metrics && autoAnalysisEnabled,
  });

  // Chat with AI Assistant (Powered by Gemini)
  const sendMessageMutation = useMutation({
    mutationFn: async (message: string) => {
      // Build context for AI
      const context = {
        tasks: {
          total: metrics?.tasks.total || 0,
          overdue: metrics?.tasks.overdue || 0,
          completed: metrics?.tasks.completed || 0,
          completion_rate: metrics?.tasks.completionRate || 0,
        },
        team: {
          total: metrics?.employees.total || 0,
          active: metrics?.employees.active || 0,
        },
        recent_issues: insights?.slice(0, 3).map(i => i.title) || [],
      };

      // Build conversation history
      const messages: AIServiceMessage[] = [
        {
          role: 'system',
          content: `You are JARVIS - an AI business analyst for a Vietnamese CEO. 

Current Company Status:
- Tasks: ${context.tasks.total} total, ${context.tasks.overdue} overdue, ${context.tasks.completed} completed (${context.tasks.completion_rate}% completion rate)
- Team: ${context.team.total} members, ${context.team.active} active
- Recent Issues: ${context.recent_issues.join(', ') || 'None'}

Guidelines:
1. Respond in Vietnamese (friendly but professional)
2. Be concise (2-4 sentences max)
3. Focus on actionable insights
4. Use emojis appropriately
5. If data is missing, acknowledge it and suggest solutions

CEO wants INSIGHTS, not raw data. Think like a strategic advisor.`,
        },
        // Include recent chat history for context
        ...chatMessages.slice(-4).map(msg => ({
          role: msg.role === 'user' ? 'user' as const : 'assistant' as const,
          content: msg.content,
        })),
        {
          role: 'user',
          content: message,
        },
      ];

      // Call AI service (Gemini)
      const aiResponse = await aiService.chat(messages);

      return {
        response: aiResponse.content,
        confidence: aiResponse.confidence,
        relatedInsights: insights?.filter(i => 
          i.priority === 'critical' || i.priority === 'high'
        ).slice(0, 2) || [],
      };
    },
    onSuccess: async (data) => {
      const assistantMessage: ChatMessage = {
        id: `msg-${Date.now()}`,
        role: 'assistant',
        content: data.response,
        timestamp: new Date(),
        insights: data.relatedInsights,
      };
      setChatMessages(prev => [...prev, assistantMessage]);
      
      // Save AI response to database
      try {
        const { data: { user } } = await supabase.auth.getUser();
        if (user) {
          const { data: company } = await supabase
            .from('companies')
            .select('id')
            .eq('owner_id', user.id)
            .single();

          if (company) {
            await supabase.from('ai_chat_history').insert({
              company_id: company.id,
              user_id: user.id,
              session_id: sessionId,
              role: 'assistant',
              content: assistantMessage.content,
              insights: data.relatedInsights || [],
              metadata: { confidence: 0.9, provider: 'openai' },
            });
          }
        }
      } catch (error) {
        console.error('Failed to save AI response:', error);
      }
    },
  });

  const handleSendMessage = async () => {
    if (!inputMessage.trim()) return;

    // INTELLIGENT AUTO-DELEGATE TRIGGER
    // Detect keywords: "giao việc", "phân công", "delegate", "assign tasks"
    const delegationKeywords = ['giao việc', 'giao 10 việc', 'phân công', 'delegate', 'assign task', 'phân bổ công việc'];
    const shouldAutoDelegate = delegationKeywords.some(keyword => 
      inputMessage.toLowerCase().includes(keyword.toLowerCase())
    );

    // DEBUG: Log detection status
    console.log('🔍 Auto-Delegate Detection:', {
      inputMessage,
      shouldAutoDelegate,
      hasMetrics: !!metrics,
      hasInsights: !!insights,
      willTrigger: shouldAutoDelegate && !!metrics && !!insights
    });

    // ALLOW AUTO-DELEGATE even without full metrics (for testing)
    // In production, you may want to require metrics && insights
    if (shouldAutoDelegate) {
      console.log('🎯 Detected delegation intent, triggering Auto-Delegate...');
      
      if (!metrics || !insights) {
        console.warn('⚠️ Auto-Delegate: Missing metrics/insights, using basic mode');
      }
      
      // Add user message to chat first
      const userMessage: ChatMessage = {
        id: `msg-${Date.now()}`,
        role: 'user',
        content: inputMessage,
        timestamp: new Date(),
      };
      setChatMessages(prev => [...prev, userMessage]);
      
      // Add AI confirmation message
      const confirmMessage: ChatMessage = {
        id: `msg-${Date.now() + 1}`,
        role: 'assistant',
        content: '🤖 Đã phát hiện yêu cầu giao việc! Đang phân tích tình hình doanh nghiệp và tạo danh sách tasks thông minh...\n\n⏳ Vui lòng chờ 2-3 giây...',
        timestamp: new Date(),
      };
      setChatMessages(prev => [...prev, confirmMessage]);
      
      // Trigger auto-delegate after short delay
      setTimeout(() => {
        handleAutoDelegateClick();
      }, 1000);
      
      setInputMessage('');
      return;
    }

    const userMessage: ChatMessage = {
      id: `msg-${Date.now()}`,
      role: 'user',
      content: inputMessage,
      timestamp: new Date(),
    };

    setChatMessages(prev => [...prev, userMessage]);
    
    // Save user message to database
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (user) {
        const { data: company } = await supabase
          .from('companies')
          .select('id')
          .eq('owner_id', user.id)
          .single();

        if (company) {
          await supabase.from('ai_chat_history').insert({
            company_id: company.id,
            user_id: user.id,
            session_id: sessionId,
            role: 'user',
            content: userMessage.content,
          });
        }
      }
    } catch (error) {
      console.error('Failed to save message:', error);
    }
    
    sendMessageMutation.mutate(inputMessage);
    setInputMessage('');
  };

  /**
   * AUTO-DELEGATE FEATURE
   * Elon Musk Philosophy: "The best meetings are no meetings. The best delegation is automatic."
   * 
   * Uses AI Assistant's complete business context to generate intelligent task suggestions:
   * - Current metrics (tasks, employees, financial health)
   * - AI insights (risks, opportunities, predictions)
   * - Workload distribution (who's overloaded, who's available)
   * - Financial trends (what needs attention NOW)
   * 
   * Result: CEO clicks button → AI generates 3-5 urgent tasks → Navigate to delegator → 1-click approve → Done!
   */
  const handleAutoDelegateClick = async () => {
    try {
      // Build business context (with fallback for missing data)
      const context = metrics && insights ? {
        // Task urgency
        overdueTasks: metrics.tasks.overdue,
        totalTasks: metrics.tasks.total,
        completionRate: metrics.tasks.completionRate,
        
        // Employee status
        activeEmployees: metrics.employees.active,
        workloadIssues: Object.entries(metrics.employees.workload || {})
          .filter(([_, wl]: [string, any]) => wl.total > 10)
          .length,
        
        // Financial health
        financialTrend: metrics.financial.trend,
        profit: metrics.financial.profit,
        
        // AI insights (critical + high priority only)
        criticalInsights: insights
          .filter(i => i.priority === 'critical' || i.priority === 'high')
          .map(i => ({
            type: i.type,
            title: i.title,
            category: i.category,
          })),
      } : null;

      // Generate AI-powered task suggestions
      const prompt = context 
        ? `Bạn là AI Assistant của CEO. Phân tích tình hình doanh nghiệp hiện tại và đề xuất 3-5 nhiệm vụ CẦN GIAO NGAY để giải quyết vấn đề:

📊 TÌNH HÌNH HIỆN TẠI:
- Tasks: ${context.overdueTasks} tasks quá hạn / ${context.totalTasks} tổng (tỉ lệ hoàn thành: ${context.completionRate}%)
- Nhân viên: ${context.activeEmployees} người đang hoạt động, ${context.workloadIssues} người có workload cao (>10 tasks)
- Tài chính: Lợi nhuận ${context.profit.toLocaleString('vi-VN')} VNĐ, xu hướng ${context.financialTrend === 'up' ? '↗️ tăng' : context.financialTrend === 'down' ? '↘️ giảm' : '→ ổn định'}
- Cảnh báo AI: ${context.criticalInsights.length} insights mức độ cao/critical

🎯 CÁC VẤN ĐỀ CẦN GIẢI QUYẾT:
${context.criticalInsights.map((insight, idx) => `${idx + 1}. [${insight.category}] ${insight.title}`).join('\n')}

📝 YÊU CẦU:
Hãy đề xuất 3-5 nhiệm vụ cụ thể để CEO giao ngay. Format:

**TASK 1: [Tiêu đề ngắn gọn]**
Mô tả: [Giải thích tại sao cần làm ngay]
Ưu tiên: high/medium
Danh mục: [operations/hr/finance/sales]
Deadline: [số ngày từ hôm nay]

**TASK 2: ...**

Lưu ý: 
- Tập trung vào vấn đề CẤP BÁC nhất
- Nhiệm vụ phải THỰC TẾ và có thể giao ngay
- Đề xuất deadline hợp lý (1-7 ngày)
- Sử dụng tiếng Việt tự nhiên`
        : `Bạn là AI Assistant của CEO. Đề xuất 5 nhiệm vụ quan trọng để quản lý doanh nghiệp hiệu quả:

📝 YÊU CẦU:
Đề xuất 5 nhiệm vụ thiết yếu cho một CEO. Format:

**TASK 1: [Tiêu đề]**
Mô tả: [Chi tiết nhiệm vụ]
Ưu tiên: high/medium
Danh mục: [operations/hr/finance/sales]
Deadline: [số ngày từ hôm nay]

Lưu ý: Sử dụng tiếng Việt tự nhiên.`;

      console.log('🤖 Auto-Delegate: Generating AI task suggestions...', { hasContext: !!context });

      const response = await aiService.chat([
        { role: 'system', content: 'Bạn là AI Assistant chuyên phân tích doanh nghiệp và đề xuất task delegation thông minh.' },
        { role: 'user', content: prompt }
      ]);

      const aiSuggestions = response.content;

      console.log('✅ Auto-Delegate: AI generated suggestions', { length: aiSuggestions.length });

      // Switch to delegator tab and pass data
      setAutoDelegateData({
        autoGenerated: aiSuggestions,
        businessContext: context,
      });
      setActiveTab('delegator');

    } catch (error) {
      console.error('❌ Auto-Delegate failed:', error);
      // Fallback: Switch to delegator tab without pre-fill
      setActiveTab('delegator');
    }
  };

  const executeAction = async (action: AIAction) => {
    try {
      console.log('🎬 Executing AI action:', action);

      // Get user and company
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const { data: company } = await supabase
        .from('companies')
        .select('id')
        .eq('owner_id', user.id)
        .single();

      if (!company) throw new Error('Company not found');

      switch (action.type) {
        case 'create_task': {
          // AUTO-CREATE TASK from AI insight
          const taskTitle = action.params.title || action.label;
          const { error: taskError } = await supabase
            .from('tasks')
            .insert({
              company_id: company.id,
              title: taskTitle,
              description: `🤖 Task tự động tạo bởi AI Assistant\n\nLý do: ${action.label}\nĐộ tin cậy: High\nNgày tạo: ${format(new Date(), 'dd/MM/yyyy HH:mm', { locale: vi })}`,
              status: 'pending',
              category: 'admin',
              priority: 'high',
              due_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days from now
              created_by: user.id,
            })
            .select()
            .single();

          if (taskError) throw taskError;

          alert(`✅ Task đã được tạo tự động: "${taskTitle}"\n\n🤖 AI đã phân tích và tạo task để giải quyết vấn đề!`);
          
          // Refresh insights after creating task
          queryClient.invalidateQueries({ queryKey: ['ceo-ai-insights'] });
          break;
        }

        case 'send_alert':
          // TODO: Implement notification system
          alert(`🔔 Đã gửi cảnh báo đến: ${action.params.recipients}\nNội dung: ${action.params.message}`);
          break;

        case 'schedule_meeting':
          // TODO: Implement calendar integration
          alert(`📅 Đã lên lịch meeting: ${action.params.topic}\n\n(Tính năng calendar đang phát triển)`);
          break;

        case 'approve':
          // TODO: Implement approval workflow
          alert(`✅ Đã approved: ${action.label}`);
          break;

        default:
          console.warn('Unknown action type:', action.type);
      }
    } catch (error) {
      console.error('❌ Action execution failed:', error);
      alert(`Lỗi khi thực hiện action: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  };

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatMessages]);

  // Load chat history on mount
  useEffect(() => {
    const loadChatHistory = async () => {
      try {
        const { data: { user } } = await supabase.auth.getUser();
        if (!user) return;

        const { data: company } = await supabase
          .from('companies')
          .select('id')
          .eq('owner_id', user.id)
          .single();

        if (!company) return;

        // Get most recent session
        const { data: recentSession } = await supabase
          .from('ai_chat_history')
          .select('session_id')
          .eq('user_id', user.id)
          .eq('company_id', company.id)
          .order('created_at', { ascending: false })
          .limit(1)
          .maybeSingle();

        if (recentSession) {
          // Load existing session
          const { data: history } = await supabase
            .from('ai_chat_history')
            .select('id, role, content, insights, created_at')
            .eq('session_id', recentSession.session_id)
            .order('created_at', { ascending: true });

          if (history && history.length > 0) {
            const loadedMessages: ChatMessage[] = history.map(h => ({
              id: h.id,
              role: h.role as 'user' | 'assistant',
              content: h.content,
              timestamp: new Date(h.created_at),
              insights: h.insights || undefined,
            }));
            setChatMessages(loadedMessages);
            setSessionId(recentSession.session_id);
            setIsLoadingHistory(false);
            return;
          }
        }

        // No history found - show welcome message
        const welcomeMsg: ChatMessage = {
          id: 'welcome',
          role: 'assistant',
          content: `Chào CEO! 👋 Tôi là AI Assistant - nghĩ như JARVIS nhưng cho business.\n\n🤖 **PREDICTIVE ANALYTICS + FINANCIAL INTELLIGENCE đã active!**\n\n✨ **Khả năng:**\n• 🔮 Dự báo vấn đề 7 ngày trước\n• 💰 Phân tích doanh thu & lợi nhuận\n• 🚨 Cảnh báo burnout & workload\n• 📊 Dự đoán cash flow\n• 🎯 Tự động tạo tasks từ insights\n\n💬 **Hỏi tôi:**\n• "Tình hình tài chính thế nào?"\n• "Có rủi ro gì không?"\n• "Dự báo dòng tiền 7 ngày tới?"\n• "Team nào overload?"`,
          timestamp: new Date(),
        };
        setChatMessages([welcomeMsg]);
        
        // Save welcome message to DB
        await supabase.from('ai_chat_history').insert({
          company_id: company.id,
          user_id: user.id,
          session_id: sessionId,
          role: 'assistant',
          content: welcomeMsg.content,
          metadata: { type: 'welcome' },
        });
      } catch (error) {
        console.error('Error loading chat history:', error);
      } finally {
        setIsLoadingHistory(false);
      }
    };

    loadChatHistory();
  }, []);

  const priorityColors = {
    low: 'bg-blue-100 text-blue-800',
    medium: 'bg-yellow-100 text-yellow-800',
    high: 'bg-orange-100 text-orange-800',
    critical: 'bg-red-100 text-red-800',
  };

  const typeIcons = {
    opportunity: TrendingUp,
    risk: AlertTriangle,
    anomaly: BarChart3,
    recommendation: Lightbulb,
    prediction: Brain,
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold flex items-center gap-3">
            <Bot className="h-8 w-8 text-purple-600" />
            CEO AI Assistant
            <Badge variant="outline" className="ml-2 text-xs">
              <Sparkles className="h-3 w-3 mr-1" />
              {aiProvider.status}
            </Badge>
          </h1>
          <p className="text-muted-foreground mt-1">
            Powered by {aiProvider.provider === 'gemini' ? 'Google Gemini' : aiProvider.provider} • Real-time analysis • Predictive insights
          </p>
        </div>
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <Switch
              checked={autoAnalysisEnabled}
              onCheckedChange={setAutoAnalysisEnabled}
              id="auto-analysis"
            />
            <Label htmlFor="auto-analysis" className="text-sm">Auto Analysis</Label>
          </div>
          <Button 
            variant="default" 
            size="sm"
            onClick={() => setActiveTab('delegator')}
            className="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 text-white font-semibold shadow-lg"
          >
            <ListTodo className="h-4 w-4 mr-2" />
            Task Delegator
          </Button>
          <Button variant="outline" size="sm">
            <Settings className="h-4 w-4 mr-2" />
            Configure
          </Button>
        </div>
      </div>

      {/* Tabs for switching between Assistant and Task Delegator */}
      <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
        <TabsList className="grid w-full max-w-md grid-cols-2">
          <TabsTrigger value="assistant" className="flex items-center gap-2">
            <Bot className="h-4 w-4" />
            AI Chat
          </TabsTrigger>
          <TabsTrigger value="delegator" className="flex items-center gap-2">
            <ListTodo className="h-4 w-4" />
            Task Delegator
          </TabsTrigger>
        </TabsList>

        <TabsContent value="assistant" className="mt-6 space-y-6">
          {/* Real-time Metrics Dashboard */}
          <div className="grid gap-4 md:grid-cols-4">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Active Team</p>
                <p className="text-2xl font-bold">{metrics?.employees.active || 0}</p>
                <p className="text-xs text-green-600 mt-1">
                  {metrics?.employees.total || 0} total
                </p>
              </div>
              <Users className="h-8 w-8 text-blue-500" />
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Task Completion</p>
                <p className="text-2xl font-bold">{metrics?.tasks.completionRate || 0}%</p>
                <p className="text-xs text-muted-foreground mt-1">
                  {metrics?.tasks.completed}/{metrics?.tasks.total} done
                </p>
              </div>
              <CheckCircle className="h-8 w-8 text-green-500" />
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">KPI Achievement</p>
                <p className="text-2xl font-bold">{metrics?.kpi.percentage || 0}%</p>
                <p className="text-xs text-muted-foreground mt-1">
                  {metrics?.kpi.achieved}/{metrics?.kpi.total} achieved
                </p>
              </div>
              <Target className="h-8 w-8 text-purple-500" />
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">AI Insights</p>
                <p className="text-2xl font-bold">{insights?.length || 0}</p>
                <p className="text-xs text-orange-600 mt-1">
                  {insights?.filter(i => i.priority === 'critical' || i.priority === 'high').length || 0} urgent
                </p>
              </div>
              <Brain className="h-8 w-8 text-orange-500" />
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        {/* AI Insights Panel */}
        <Card className="lg:col-span-1">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-yellow-500" />
              AI Insights
            </CardTitle>
            <CardDescription>Real-time intelligence from your data</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3 max-h-[600px] overflow-y-auto">
            {insightsLoading ? (
              <p className="text-center text-muted-foreground py-8">Analyzing...</p>
            ) : insights && insights.length > 0 ? (
              insights.map((insight) => {
                const IconComponent = typeIcons[insight.type];
                return (
                  <div key={insight.id} className="border rounded-lg p-4 space-y-3">
                    <div className="flex items-start justify-between">
                      <div className="flex items-start gap-2 flex-1">
                        <IconComponent className="h-5 w-5 mt-0.5 flex-shrink-0" />
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-1">
                            <Badge className={cn('text-xs', priorityColors[insight.priority])}>
                              {insight.priority}
                            </Badge>
                            <span className="text-xs text-muted-foreground">
                              {Math.round(insight.confidence * 100)}% confidence
                            </span>
                          </div>
                          <h4 className="font-semibold text-sm mb-1">{insight.title}</h4>
                          <p className="text-xs text-muted-foreground">{insight.description}</p>
                        </div>
                      </div>
                    </div>
                    
                    {insight.actions.length > 0 && (
                      <div className="space-y-1 pt-2 border-t">
                        {insight.actions.map((action) => (
                          <Button
                            key={action.id}
                            variant="outline"
                            size="sm"
                            className="w-full justify-start text-xs h-8"
                            onClick={() => executeAction(action)}
                          >
                            <Play className="h-3 w-3 mr-2" />
                            {action.label}
                          </Button>
                        ))}
                      </div>
                    )}
                  </div>
                );
              })
            ) : (
              <div className="text-center py-8 text-muted-foreground">
                <Brain className="h-12 w-12 mx-auto mb-3 opacity-50" />
                <p className="text-sm">No critical insights right now</p>
                <p className="text-xs">Everything looks good! 🎉</p>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Chat Interface */}
        <Card className="lg:col-span-2">
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle className="flex items-center gap-2">
                  <MessageSquare className="h-5 w-5" />
                  Chat with AI Assistant
                </CardTitle>
                <CardDescription>Ask anything about your business • Lịch sử được lưu tự động</CardDescription>
              </div>
              <Button
                variant="outline"
                size="sm"
                onClick={() => {
                  const newSessionId = crypto.randomUUID();
                  setSessionId(newSessionId);
                  setChatMessages([]);
                  setIsLoadingHistory(false);
                }}
                className="flex items-center gap-2"
              >
                <RefreshCw className="h-4 w-4" />
                New Chat
              </Button>
            </div>
          </CardHeader>
          <CardContent>
            {/* Chat Messages */}
            <div className="space-y-4 mb-4 h-[500px] overflow-y-auto border rounded-lg p-4 bg-gray-50">
              {chatMessages.map((message) => (
                <div
                  key={message.id}
                  className={cn(
                    'flex gap-3',
                    message.role === 'user' ? 'justify-end' : 'justify-start'
                  )}
                >
                  {message.role === 'assistant' && (
                    <div className="flex-shrink-0">
                      <div className="w-8 h-8 rounded-full bg-purple-600 flex items-center justify-center">
                        <Bot className="h-5 w-5 text-white" />
                      </div>
                    </div>
                  )}
                  <div
                    className={cn(
                      'max-w-[80%] rounded-lg p-3',
                      message.role === 'user'
                        ? 'bg-blue-600 text-white'
                        : 'bg-white border'
                    )}
                  >
                    <p className="text-sm whitespace-pre-wrap">{message.content}</p>
                    <div className="flex items-center justify-between mt-2">
                      <p className="text-xs opacity-70">
                        {format(message.timestamp, 'HH:mm', { locale: vi })}
                      </p>
                      {message.role === 'assistant' && message.content.length > 100 && (
                        <Button
                          variant="ghost"
                          size="sm"
                          className="h-6 text-xs text-purple-600 hover:text-purple-800 hover:bg-purple-50 px-2"
                          onClick={() => handleSendToTaskDelegator(message.content)}
                        >
                          <ArrowRight className="h-3 w-3 mr-1" />
                          Chuyển sang Task Delegator
                        </Button>
                      )}
                    </div>
                  </div>
                  {message.role === 'user' && (
                    <div className="flex-shrink-0">
                      <div className="w-8 h-8 rounded-full bg-blue-600 flex items-center justify-center text-white font-bold">
                        C
                      </div>
                    </div>
                  )}
                </div>
              ))}
              <div ref={chatEndRef} />
            </div>

            {/* Input */}
            <div className="flex gap-2">
              <Input
                placeholder="Hỏi tôi về doanh thu, team performance, KPI, hoặc bất cứ gì..."
                value={inputMessage}
                onChange={(e) => setInputMessage(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && !e.shiftKey && handleSendMessage()}
                disabled={sendMessageMutation.isPending}
              />
              <Button
                onClick={handleSendMessage}
                disabled={sendMessageMutation.isPending || !inputMessage.trim()}
              >
                {sendMessageMutation.isPending ? (
                  <RefreshCw className="h-4 w-4 animate-spin" />
                ) : (
                  <Send className="h-4 w-4" />
                )}
              </Button>
            </div>

            {/* Quick Suggestions */}
            <div className="flex flex-wrap gap-2 mt-3">
              {[
                'Tình hình doanh thu thế nào?',
                'Team perform ra sao?',
                'Có task nào quá hạn?',
                'Đề xuất action cho tuần này',
              ].map((suggestion) => (
                <Button
                  key={suggestion}
                  variant="outline"
                  size="sm"
                  className="text-xs"
                  onClick={() => {
                    setInputMessage(suggestion);
                    setTimeout(() => handleSendMessage(), 100);
                  }}
                  disabled={sendMessageMutation.isPending}
                >
                  {suggestion}
                </Button>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </TabsContent>

    <TabsContent value="delegator" className="mt-6">
      <TaskDelegatorContent autoDelegateData={autoDelegateData} onDataConsumed={() => setAutoDelegateData(null)} />
    </TabsContent>
  </Tabs>
</div>
);
}

// ============================================
// EMBEDDED TASK DELEGATOR COMPONENT
// ============================================

interface ParsedTask {
  id: string;
  title: string;
  description: string;
  category: string;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  estimatedHours: number;
  suggestedEmployee: {
    id: string;
    name: string;
    role: string;
    currentWorkload: number;
    matchScore: number;
    reason: string;
  } | null;
  instructions: string[];
  dueDate: string;
  status: 'pending' | 'approved' | 'rejected';
}

interface Employee {
  id: string;
  full_name: string;
  role: string;
  currentTasks: number;
}

interface TaskDelegatorContentProps {
  autoDelegateData?: { autoGenerated: string; businessContext: any } | null;
  onDataConsumed?: () => void;
}

function TaskDelegatorContent({ autoDelegateData, onDataConsumed }: TaskDelegatorContentProps) {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [rawInput, setRawInput] = useState('');
  const [parsedTasks, setParsedTasks] = useState<ParsedTask[]>([]);
  const [isAnalyzing, setIsAnalyzing] = useState(false);

  // Auto-fill from AI Assistant's auto-delegate feature
  useEffect(() => {
    if (autoDelegateData?.autoGenerated) {
      console.log('🎯 Auto-Delegate: Received AI-generated tasks', {
        length: autoDelegateData.autoGenerated.length,
        context: autoDelegateData.businessContext
      });

      setRawInput(autoDelegateData.autoGenerated);
      onDataConsumed?.(); // Clear the data after consuming

      toast({
        title: '🤖 AI Auto-Delegate Activated',
        description: `AI đã phân tích tình hình doanh nghiệp và đề xuất tasks cần giao ngay.`,
        duration: 5000,
      });
    }
  }, [autoDelegateData]);

  // Fetch employees for assignment
  const { data: employees } = useQuery<Employee[]>({
    queryKey: ['employees-for-delegation'],
    queryFn: async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const { data: company } = await supabase
        .from('companies')
        .select('id')
        .eq('owner_id', user.id)
        .single();

      if (!company) throw new Error('Company not found');

      const { data: employeesList } = await supabase
        .from('employees')
        .select('id, full_name, role')
        .eq('company_id', company.id)
        .eq('is_active', true)
        .is('deleted_at', null);

      const employeesWithWorkload = await Promise.all(
        (employeesList || []).map(async (emp) => {
          const { count } = await supabase
            .from('tasks')
            .select('*', { count: 'exact', head: true })
            .eq('assigned_to', emp.id)
            .neq('status', 'completed')
            .is('deleted_at', null);

          return { ...emp, currentTasks: count || 0 };
        })
      );

      return employeesWithWorkload;
    },
  });

  const analyzeTasks = async () => {
    if (!rawInput.trim()) {
      toast({ title: 'Vui lòng nhập danh sách công việc', variant: 'destructive' });
      return;
    }

    setIsAnalyzing(true);

    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const prompt = `You are an AI Task Manager for a CEO. Parse this natural language task list and create structured tasks.

TASK LIST:
${rawInput}

AVAILABLE EMPLOYEES:
${employees?.map(e => `- ${e.full_name} (${e.role}): Currently has ${e.currentTasks} active tasks`).join('\n')}

RETURN JSON ARRAY with this structure for EACH task:
[
  {
    "title": "Clear, actionable task title (Vietnamese)",
    "description": "Detailed description (Vietnamese)",
    "category": "marketing|operations|admin|sales|other",
    "priority": "low|medium|high",
    "estimatedHours": number,
    "suggestedEmployeeId": "employee_id or null",
    "matchReason": "Why this employee is best fit (Vietnamese)",
    "matchScore": 0-100,
    "instructions": ["Step 1", "Step 2", "Step 3"],
    "dueDate": "YYYY-MM-DD"
  }
]

RULES:
1. Parse Vietnamese naturally
2. Break down vague tasks into specific actionable items
3. Suggest employee based on role + current workload
4. Add clear step-by-step instructions
5. Estimate realistic hours
6. Smart due dates (daily = today, weekly = end of week)
7. If no suitable employee, suggestedEmployeeId = null
8. Use "high" priority for urgent tasks

RETURN ONLY THE JSON ARRAY, NO MARKDOWN, NO EXPLANATION.`;

      const response = await aiService.chat([{ role: 'user', content: prompt }]);

      let aiTasks;
      try {
        const responseContent = response.content || '';
        const cleanedContent = responseContent.replace(/```json\s*/gi, '').replace(/```\s*/g, '').trim();
        const jsonMatch = cleanedContent.match(/\[[\s\S]*\]/);
        if (jsonMatch) {
          aiTasks = JSON.parse(jsonMatch[0]);
        } else {
          aiTasks = JSON.parse(cleanedContent);
        }
      } catch (parseError) {
        console.error('Failed to parse AI response:', response);
        throw new Error('AI response không hợp lệ. Vui lòng thử lại.');
      }

      const parsed: ParsedTask[] = aiTasks.map((task: any, index: number) => {
        const suggestedEmp = employees?.find(e => e.id === task.suggestedEmployeeId);
        return {
          id: `task-${Date.now()}-${index}`,
          title: task.title,
          description: task.description,
          category: task.category,
          priority: task.priority,
          estimatedHours: task.estimatedHours,
          suggestedEmployee: suggestedEmp ? {
            id: suggestedEmp.id,
            name: suggestedEmp.full_name,
            role: suggestedEmp.role,
            currentWorkload: suggestedEmp.currentTasks,
            matchScore: task.matchScore,
            reason: task.matchReason,
          } : null,
          instructions: task.instructions,
          dueDate: task.dueDate,
          status: 'pending' as const,
        };
      });

      setParsedTasks(parsed);
      toast({ title: '✅ Phân tích thành công!', description: `AI đã tạo ${parsed.length} tasks từ input của bạn` });
    } catch (error) {
      console.error('Analysis failed:', error);
      toast({ title: 'Lỗi phân tích', description: error instanceof Error ? error.message : 'Không thể phân tích tasks', variant: 'destructive' });
    } finally {
      setIsAnalyzing(false);
    }
  };

  const createTasksMutation = useMutation({
    mutationFn: async (tasksToCreate: ParsedTask[]) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const { data: company } = await supabase.from('companies').select('id').eq('owner_id', user.id).single();
      if (!company) throw new Error('Company not found');

      const tasksData = tasksToCreate.map(task => {
        const validPriority = task.priority === 'urgent' ? 'high' : task.priority;
        const assignedEmployee = task.suggestedEmployee;
        return {
          company_id: company.id,
          title: task.title,
          description: `${task.description}\n\n**📋 HƯỚNG DẪN THỰC HIỆN:**\n${task.instructions.map((inst, i) => `${i + 1}. ${inst}`).join('\n')}\n\n⏱️ Ước tính: ${task.estimatedHours}h\n🤖 AI-generated task`,
          category: task.category,
          priority: validPriority,
          status: 'pending',
          assigned_to: assignedEmployee?.id || null,
          assigned_to_name: assignedEmployee?.name || null,
          assigned_to_role: assignedEmployee?.role || null,
          due_date: task.dueDate || null,
          created_by: user.id,
        };
      });

      const { data, error } = await supabase.from('tasks').insert(tasksData).select();
      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      toast({ title: '🎉 Tasks đã được tạo!', description: `${data.length} tasks đã giao cho nhân viên thành công` });
      setRawInput('');
      setParsedTasks([]);
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
      queryClient.invalidateQueries({ queryKey: ['employees-for-delegation'] });
    },
    onError: (error) => {
      toast({ title: 'Lỗi tạo tasks', description: error instanceof Error ? error.message : 'Không thể tạo tasks', variant: 'destructive' });
    },
  });

  const approveTask = (taskId: string) => setParsedTasks(prev => prev.map(t => t.id === taskId ? { ...t, status: 'approved' as const } : t));
  const rejectTask = (taskId: string) => setParsedTasks(prev => prev.map(t => t.id === taskId ? { ...t, status: 'rejected' as const } : t));
  const approveAll = () => setParsedTasks(prev => prev.map(t => ({ ...t, status: 'approved' as const })));

  const handleCreateTasks = () => {
    const approved = parsedTasks.filter(t => t.status === 'approved');
    if (approved.length === 0) {
      toast({ title: 'Chưa có task nào được approve', variant: 'destructive' });
      return;
    }
    createTasksMutation.mutate(approved);
  };

  const priorityColors = {
    low: 'bg-blue-100 text-blue-800',
    medium: 'bg-yellow-100 text-yellow-800',
    high: 'bg-orange-100 text-orange-800',
    urgent: 'bg-red-100 text-red-800',
  };

  const categoryIcons: Record<string, string> = {
    marketing: '📱', operations: '⚙️', admin: '📋', sales: '💰', other: '📌',
  };

  return (
    <div className="space-y-6">
      {/* Stats */}
      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Active Employees</p>
                <p className="text-2xl font-bold">{employees?.length || 0}</p>
              </div>
              <Users className="h-8 w-8 text-blue-500" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Tasks Analyzed</p>
                <p className="text-2xl font-bold">{parsedTasks.length}</p>
              </div>
              <Brain className="h-8 w-8 text-purple-500" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Ready to Create</p>
                <p className="text-2xl font-bold">{parsedTasks.filter(t => t.status === 'approved').length}</p>
              </div>
              <CheckCircle className="h-8 w-8 text-green-500" />
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* Input Section */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Zap className="h-5 w-5 text-yellow-500" />
              Natural Language Input
            </CardTitle>
            <CardDescription>Paste công việc bằng tiếng Việt tự nhiên. AI sẽ hiểu!</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <Textarea
              placeholder={`Ví dụ:\n\n- Đăng 10 bài poster lên Facebook/ngày\n- Dựng 1 video TikTok về sản phẩm mới\n- Kiểm kho hàng tồn kho cuối tuần\n- Báo cáo doanh thu tuần này\n- Gọi điện cho 20 khách hàng tiềm năng`}
              value={rawInput}
              onChange={(e) => setRawInput(e.target.value)}
              className="min-h-[250px] font-mono text-sm"
              disabled={isAnalyzing}
            />
            <div className="flex gap-2">
              <Button onClick={analyzeTasks} disabled={!rawInput.trim() || isAnalyzing} className="flex-1">
                {isAnalyzing ? <><RefreshCw className="mr-2 h-4 w-4 animate-spin" />AI đang phân tích...</> : <><Brain className="mr-2 h-4 w-4" />Phân Tích với AI</>}
              </Button>
              {parsedTasks.length > 0 && (
                <Button variant="outline" onClick={() => { setRawInput(''); setParsedTasks([]); }}>Reset</Button>
              )}
            </div>
          </CardContent>
        </Card>

        {/* Results Section */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-purple-500" />
              AI Analysis Results
            </CardTitle>
            <CardDescription>Review & approve tasks trước khi giao</CardDescription>
          </CardHeader>
          <CardContent>
            {parsedTasks.length === 0 ? (
              <div className="text-center py-12 text-muted-foreground">
                <Brain className="h-12 w-12 mx-auto mb-3 opacity-50" />
                <p className="text-sm">Chưa có tasks nào</p>
                <p className="text-xs">Paste công việc bên trái và click "Phân Tích"</p>
              </div>
            ) : (
              <div className="space-y-4">
                <div className="flex gap-2">
                  <Button size="sm" variant="outline" onClick={approveAll} className="flex-1">
                    <CheckCircle className="mr-2 h-4 w-4" />Approve All
                  </Button>
                  <Button size="sm" onClick={handleCreateTasks} disabled={parsedTasks.filter(t => t.status === 'approved').length === 0 || createTasksMutation.isPending} className="flex-1">
                    {createTasksMutation.isPending ? <RefreshCw className="mr-2 h-4 w-4 animate-spin" /> : <Send className="mr-2 h-4 w-4" />}
                    Create Tasks ({parsedTasks.filter(t => t.status === 'approved').length})
                  </Button>
                </div>
                <div className="space-y-3 max-h-[400px] overflow-y-auto">
                  {parsedTasks.map((task) => (
                    <div key={task.id} className={cn('border rounded-lg p-4 space-y-3 transition-all', task.status === 'approved' && 'border-green-500 bg-green-50', task.status === 'rejected' && 'border-red-500 bg-red-50 opacity-50')}>
                      <div className="flex items-start justify-between gap-2">
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-1">
                            <span className="text-xl">{categoryIcons[task.category] || '📌'}</span>
                            <h4 className="font-semibold text-sm">{task.title}</h4>
                          </div>
                          <p className="text-xs text-muted-foreground">{task.description}</p>
                        </div>
                        <Badge className={cn('text-xs', priorityColors[task.priority])}>{task.priority}</Badge>
                      </div>
                      {task.suggestedEmployee && (
                        <div className="bg-blue-50 border border-blue-200 rounded p-2 text-xs">
                          <div className="flex items-center justify-between mb-1">
                            <div className="flex items-center gap-2">
                              <Users className="h-3 w-3 text-blue-600" />
                              <span className="font-semibold">{task.suggestedEmployee.name}</span>
                              <Badge variant="outline" className="text-xs">{task.suggestedEmployee.role}</Badge>
                            </div>
                            <span className="text-blue-600 font-semibold">Match: {task.suggestedEmployee.matchScore}%</span>
                          </div>
                          <p className="text-muted-foreground">{task.suggestedEmployee.reason}</p>
                        </div>
                      )}
                      <div className="flex gap-2 pt-2 border-t">
                        <Button size="sm" variant={task.status === 'approved' ? 'default' : 'outline'} onClick={() => approveTask(task.id)} disabled={task.status === 'approved'} className="flex-1">
                          <CheckCircle className="mr-1 h-3 w-3" />{task.status === 'approved' ? 'Approved' : 'Approve'}
                        </Button>
                        <Button size="sm" variant="outline" onClick={() => rejectTask(task.id)} disabled={task.status === 'rejected'} className="flex-1">
                          <AlertTriangle className="mr-1 h-3 w-3" />{task.status === 'rejected' ? 'Rejected' : 'Reject'}
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}