import { useState, useEffect } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocation } from 'react-router-dom';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Textarea } from '@/components/ui/textarea';
import { 
  Sparkles, 
  Send, 
  CheckCircle, 
  Clock, 
  User, 
  Brain,
  Zap,
  AlertCircle,
  ArrowRight,
  RefreshCw,
  Check,
  X,
} from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { aiService } from '@/services/aiService';
import { useToast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';

interface ParsedTask {
  id: string;
  title: string;
  description: string;
  category: string;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  estimatedHours: number;
  suggestedEmployee: {
    id: string;
    name: string;
    role: string;
    currentWorkload: number;
    matchScore: number;
    reason: string;
  } | null;
  instructions: string[];
  dueDate: string;
  status: 'pending' | 'approved' | 'rejected';
}

interface Employee {
  id: string;
  full_name: string;
  role: string;
  currentTasks: number;
}

/**
 * AI TASK DELEGATOR - Elon Musk Philosophy
 * 
 * "The best interface is no interface" - AI should understand natural language
 * "Automate everything" - From parsing to assignment to tracking
 * "Speed matters" - From CEO idea to employee task in 30 seconds
 * 
 * WORKFLOW:
 * 1. CEO pastes natural language task list
 * 2. AI parses, categorizes, suggests best employee
 * 3. CEO reviews & approves (1-click)
 * 4. Tasks auto-assigned with instructions
 * 5. Real-time progress tracking
 */
export default function AITaskDelegator() {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const location = useLocation();
  const [rawInput, setRawInput] = useState('');
  const [parsedTasks, setParsedTasks] = useState<ParsedTask[]>([]);
  const [isAnalyzing, setIsAnalyzing] = useState(false);

  // Auto-fill from AI Assistant's auto-delegate feature
  useEffect(() => {
    const autoGenerated = location.state?.autoGenerated;
    const businessContext = location.state?.businessContext;

    if (autoGenerated) {
      console.log('🎯 Auto-Delegate: Received AI-generated tasks', { 
        length: autoGenerated.length,
        context: businessContext 
      });

      setRawInput(autoGenerated);

      // Auto-trigger analysis after a short delay (let user see the pre-filled content)
      setTimeout(() => {
        analyzeTasks();
      }, 500);

      // Show toast notification
      toast({
        title: '🤖 AI Auto-Delegate Activated',
        description: `AI đã phân tích tình hình doanh nghiệp và đề xuất ${businessContext?.criticalInsights?.length || 'nhiều'} tasks cần giao ngay. Đang xử lý...`,
        duration: 5000,
      });
    }
  }, [location.state]);

  // Fetch employees for assignment
  const { data: employees } = useQuery<Employee[]>({
    queryKey: ['employees-for-delegation'],
    queryFn: async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const { data: company } = await supabase
        .from('companies')
        .select('id')
        .eq('owner_id', user.id)
        .single();

      if (!company) throw new Error('Company not found');

      // Get employees with their current task count
      const { data: employeesList } = await supabase
        .from('employees')
        .select('id, full_name, role')
        .eq('company_id', company.id)
        .eq('is_active', true)
        .is('deleted_at', null);

      // Count current tasks for each employee
      const employeesWithWorkload = await Promise.all(
        (employeesList || []).map(async (emp) => {
          const { count } = await supabase
            .from('tasks')
            .select('*', { count: 'exact', head: true })
            .eq('assigned_to', emp.id)
            .neq('status', 'completed')
            .is('deleted_at', null);

          return {
            ...emp,
            currentTasks: count || 0,
          };
        })
      );

      return employeesWithWorkload;
    },
  });

  // AI Parse & Analyze Tasks
  const analyzeTasks = async () => {
    if (!rawInput.trim()) {
      toast({ title: 'Vui lòng nhập danh sách công việc', variant: 'destructive' });
      return;
    }

    setIsAnalyzing(true);

    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const { data: company } = await supabase
        .from('companies')
        .select('id')
        .eq('owner_id', user.id)
        .single();

      if (!company) throw new Error('Company not found');

      // Call AI to parse and analyze
      const prompt = `You are an AI Task Manager for a CEO. Parse this natural language task list and create structured tasks.

TASK LIST:
${rawInput}

AVAILABLE EMPLOYEES:
${employees?.map(e => `- ${e.full_name} (${e.role}): Currently has ${e.currentTasks} active tasks`).join('\n')}

RETURN JSON ARRAY with this structure for EACH task:
[
  {
    "title": "Clear, actionable task title (Vietnamese)",
    "description": "Detailed description (Vietnamese)",
    "category": "marketing|operations|admin|sales|other",
    "priority": "low|medium|high",
    "estimatedHours": number,
    "suggestedEmployeeId": "employee_id or null",
    "matchReason": "Why this employee is best fit (Vietnamese)",
    "matchScore": 0-100,
    "instructions": ["Step 1", "Step 2", "Step 3"],
    "dueDate": "YYYY-MM-DD"
  }
]

RULES:
1. Parse Vietnamese naturally (đăng poster = Post social media content)
2. Break down vague tasks into specific actionable items
3. Suggest employee based on role + current workload (balance load!)
4. Add clear step-by-step instructions
5. Estimate realistic hours
6. Smart due dates (daily tasks = today, weekly = end of week)
7. If no suitable employee, suggestedEmployeeId = null
8. Use "high" priority for urgent/critical tasks (not "urgent")

RETURN ONLY THE JSON ARRAY, NO MARKDOWN, NO EXPLANATION.`;

      const response = await aiService.chat([
        { role: 'user', content: prompt }
      ]);

      // Parse AI response - response is { content: string, confidence: number }
      let aiTasks;
      try {
        const responseContent = response.content || '';
        // Remove markdown code blocks if present
        const cleanedContent = responseContent
          .replace(/```json\s*/gi, '')
          .replace(/```\s*/g, '')
          .trim();
        
        const jsonMatch = cleanedContent.match(/\[[\s\S]*\]/);
        if (jsonMatch) {
          aiTasks = JSON.parse(jsonMatch[0]);
        } else {
          aiTasks = JSON.parse(cleanedContent);
        }
      } catch (parseError) {
        console.error('Failed to parse AI response:', response);
        throw new Error('AI response không hợp lệ. Vui lòng thử lại.');
      }

      // Map to ParsedTask format
      const parsed: ParsedTask[] = aiTasks.map((task: any, index: number) => {
        const suggestedEmp = employees?.find(e => e.id === task.suggestedEmployeeId);
        
        return {
          id: `task-${Date.now()}-${index}`,
          title: task.title,
          description: task.description,
          category: task.category,
          priority: task.priority,
          estimatedHours: task.estimatedHours,
          suggestedEmployee: suggestedEmp ? {
            id: suggestedEmp.id,
            name: suggestedEmp.full_name,
            role: suggestedEmp.role,
            currentWorkload: suggestedEmp.currentTasks,
            matchScore: task.matchScore,
            reason: task.matchReason,
          } : null,
          instructions: task.instructions,
          dueDate: task.dueDate,
          status: 'pending' as const,
        };
      });

      setParsedTasks(parsed);
      
      toast({
        title: '✅ Phân tích thành công!',
        description: `AI đã tạo ${parsed.length} tasks từ input của bạn`,
      });
    } catch (error) {
      console.error('Analysis failed:', error);
      toast({
        title: 'Lỗi phân tích',
        description: error instanceof Error ? error.message : 'Không thể phân tích tasks',
        variant: 'destructive',
      });
    } finally {
      setIsAnalyzing(false);
    }
  };

  // Approve & Create Tasks
  const createTasksMutation = useMutation({
    mutationFn: async (tasksToCreate: ParsedTask[]) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      // Get company ID for the current user
      const { data: company } = await supabase
        .from('companies')
        .select('id')
        .eq('owner_id', user.id)
        .single();

      if (!company) throw new Error('Company not found');

      // Create all approved tasks
      const tasksData = tasksToCreate.map(task => {
        // Map 'urgent' priority to 'high' (schema only allows low/medium/high)
        const validPriority = task.priority === 'urgent' ? 'high' : task.priority;
        
        // Get employee details for assigned_to_name and assigned_to_role
        const assignedEmployee = task.suggestedEmployee;
        
        return {
          company_id: company.id,
          title: task.title,
          description: `${task.description}\n\n**📋 HƯỚNG DẪN THỰC HIỆN:**\n${task.instructions.map((inst, i) => `${i + 1}. ${inst}`).join('\n')}\n\n⏱️ Ước tính: ${task.estimatedHours}h\n🤖 AI-generated task`,
          category: task.category,
          priority: validPriority,
          status: 'pending',
          assigned_to: assignedEmployee?.id || null,
          assigned_to_name: assignedEmployee?.name || null,
          assigned_to_role: assignedEmployee?.role || null,
          due_date: task.dueDate || null,
          created_by: user.id,
        };
      });

      const { data, error } = await supabase
        .from('tasks')
        .insert(tasksData)
        .select();

      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      toast({
        title: '🎉 Tasks đã được tạo!',
        description: `${data.length} tasks đã giao cho nhân viên thành công`,
      });
      
      // Reset
      setRawInput('');
      setParsedTasks([]);
      
      // Refresh data
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
      queryClient.invalidateQueries({ queryKey: ['employees-for-delegation'] });
    },
    onError: (error) => {
      toast({
        title: 'Lỗi tạo tasks',
        description: error instanceof Error ? error.message : 'Không thể tạo tasks',
        variant: 'destructive',
      });
    },
  });

  const approveTask = (taskId: string) => {
    setParsedTasks(prev => 
      prev.map(t => t.id === taskId ? { ...t, status: 'approved' as const } : t)
    );
  };

  const rejectTask = (taskId: string) => {
    setParsedTasks(prev => 
      prev.map(t => t.id === taskId ? { ...t, status: 'rejected' as const } : t)
    );
  };

  const approveAll = () => {
    setParsedTasks(prev => prev.map(t => ({ ...t, status: 'approved' as const })));
  };

  const handleCreateTasks = () => {
    const approved = parsedTasks.filter(t => t.status === 'approved');
    if (approved.length === 0) {
      toast({ title: 'Chưa có task nào được approve', variant: 'destructive' });
      return;
    }
    createTasksMutation.mutate(approved);
  };

  const priorityColors = {
    low: 'bg-blue-100 text-blue-800',
    medium: 'bg-yellow-100 text-yellow-800',
    high: 'bg-orange-100 text-orange-800',
    urgent: 'bg-red-100 text-red-800',
  };

  const categoryIcons = {
    marketing: '📱',
    operations: '⚙️',
    admin: '📋',
    sales: '💰',
    other: '📌',
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold flex items-center gap-3">
          <Sparkles className="h-8 w-8 text-purple-600" />
          AI Task Delegator
        </h1>
        <p className="text-muted-foreground mt-2">
          Paste danh sách công việc bằng ngôn ngữ tự nhiên → AI tự động phân tích & giao việc
        </p>
      </div>

      {/* Stats */}
      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Active Employees</p>
                <p className="text-2xl font-bold">{employees?.length || 0}</p>
              </div>
              <User className="h-8 w-8 text-blue-500" />
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Tasks Analyzed</p>
                <p className="text-2xl font-bold">{parsedTasks.length}</p>
              </div>
              <Brain className="h-8 w-8 text-purple-500" />
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Ready to Create</p>
                <p className="text-2xl font-bold">
                  {parsedTasks.filter(t => t.status === 'approved').length}
                </p>
              </div>
              <CheckCircle className="h-8 w-8 text-green-500" />
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* Input Section */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Zap className="h-5 w-5 text-yellow-500" />
              Natural Language Input
            </CardTitle>
            <CardDescription>
              Paste công việc bằng tiếng Việt tự nhiên. AI sẽ hiểu!
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <Textarea
              placeholder={`Ví dụ:\n\n- Đăng 10 bài poster lên Facebook/ngày\n- Dựng 1 video TikTok về sản phẩm mới\n- Kiểm kho hàng tồn kho cuối tuần\n- Báo cáo doanh thu tuần này\n- Gọi điện cho 20 khách hàng tiềm năng\n- Chuẩn bị slides cho họp team\n\nAI sẽ tự động:\n✓ Phân loại category\n✓ Đánh giá độ ưu tiên\n✓ Gợi ý nhân viên phù hợp\n✓ Tạo hướng dẫn chi tiết`}
              value={rawInput}
              onChange={(e) => setRawInput(e.target.value)}
              className="min-h-[300px] font-mono text-sm"
              disabled={isAnalyzing}
            />

            <div className="flex gap-2">
              <Button
                onClick={analyzeTasks}
                disabled={!rawInput.trim() || isAnalyzing}
                className="flex-1"
              >
                {isAnalyzing ? (
                  <>
                    <RefreshCw className="mr-2 h-4 w-4 animate-spin" />
                    AI đang phân tích...
                  </>
                ) : (
                  <>
                    <Brain className="mr-2 h-4 w-4" />
                    Phân Tích với AI
                  </>
                )}
              </Button>

              {parsedTasks.length > 0 && (
                <Button
                  variant="outline"
                  onClick={() => {
                    setRawInput('');
                    setParsedTasks([]);
                  }}
                >
                  Reset
                </Button>
              )}
            </div>

            <div className="text-xs text-muted-foreground space-y-1">
              <p>💡 <strong>Tips:</strong></p>
              <p>• Viết tự nhiên như nói chuyện</p>
              <p>• AI hiểu cả slang: "quay clip", "chốt đơn"</p>
              <p>• Nếu không chỉ rõ deadline → AI tự động gợi ý</p>
            </div>
          </CardContent>
        </Card>

        {/* Analysis Results */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-purple-500" />
              AI Analysis Results
            </CardTitle>
            <CardDescription>
              Review & approve tasks trước khi giao
            </CardDescription>
          </CardHeader>
          <CardContent>
            {parsedTasks.length === 0 ? (
              <div className="text-center py-12 text-muted-foreground">
                <Brain className="h-12 w-12 mx-auto mb-3 opacity-50" />
                <p className="text-sm">Chưa có tasks nào</p>
                <p className="text-xs">Paste công việc bên trái và click "Phân Tích"</p>
              </div>
            ) : (
              <div className="space-y-4">
                {/* Bulk Actions */}
                <div className="flex gap-2">
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={approveAll}
                    className="flex-1"
                  >
                    <Check className="mr-2 h-4 w-4" />
                    Approve All
                  </Button>
                  <Button
                    size="sm"
                    onClick={handleCreateTasks}
                    disabled={parsedTasks.filter(t => t.status === 'approved').length === 0 || createTasksMutation.isPending}
                    className="flex-1"
                  >
                    {createTasksMutation.isPending ? (
                      <RefreshCw className="mr-2 h-4 w-4 animate-spin" />
                    ) : (
                      <Send className="mr-2 h-4 w-4" />
                    )}
                    Create Tasks ({parsedTasks.filter(t => t.status === 'approved').length})
                  </Button>
                </div>

                {/* Tasks List */}
                <div className="space-y-3 max-h-[600px] overflow-y-auto">
                  {parsedTasks.map((task) => (
                    <div
                      key={task.id}
                      className={cn(
                        'border rounded-lg p-4 space-y-3 transition-all',
                        task.status === 'approved' && 'border-green-500 bg-green-50',
                        task.status === 'rejected' && 'border-red-500 bg-red-50 opacity-50'
                      )}
                    >
                      {/* Title & Priority */}
                      <div className="flex items-start justify-between gap-2">
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-1">
                            <span className="text-xl">{categoryIcons[task.category as keyof typeof categoryIcons]}</span>
                            <h4 className="font-semibold text-sm">{task.title}</h4>
                          </div>
                          <p className="text-xs text-muted-foreground">{task.description}</p>
                        </div>
                        <Badge className={cn('text-xs', priorityColors[task.priority])}>
                          {task.priority}
                        </Badge>
                      </div>

                      {/* Assignment Suggestion */}
                      {task.suggestedEmployee ? (
                        <div className="bg-blue-50 border border-blue-200 rounded p-2 text-xs">
                          <div className="flex items-center justify-between mb-1">
                            <div className="flex items-center gap-2">
                              <User className="h-3 w-3 text-blue-600" />
                              <span className="font-semibold">{task.suggestedEmployee.name}</span>
                              <Badge variant="outline" className="text-xs">
                                {task.suggestedEmployee.role}
                              </Badge>
                            </div>
                            <span className="text-blue-600 font-semibold">
                              Match: {task.suggestedEmployee.matchScore}%
                            </span>
                          </div>
                          <p className="text-muted-foreground">
                            {task.suggestedEmployee.reason}
                          </p>
                          <p className="text-muted-foreground mt-1">
                            Current workload: {task.suggestedEmployee.currentWorkload} tasks
                          </p>
                        </div>
                      ) : (
                        <div className="bg-yellow-50 border border-yellow-200 rounded p-2 text-xs">
                          <AlertCircle className="h-3 w-3 inline text-yellow-600 mr-1" />
                          <span className="text-yellow-700">Chưa có nhân viên phù hợp. Sẽ để unassigned.</span>
                        </div>
                      )}

                      {/* Meta info */}
                      <div className="flex items-center gap-4 text-xs text-muted-foreground">
                        <span className="flex items-center gap-1">
                          <Clock className="h-3 w-3" />
                          {task.estimatedHours}h
                        </span>
                        <span>Due: {task.dueDate}</span>
                      </div>

                      {/* Instructions Preview */}
                      <details className="text-xs">
                        <summary className="cursor-pointer text-blue-600 hover:underline">
                          View Instructions ({task.instructions.length} steps)
                        </summary>
                        <ol className="list-decimal list-inside mt-2 space-y-1 text-muted-foreground">
                          {task.instructions.map((inst, i) => (
                            <li key={i}>{inst}</li>
                          ))}
                        </ol>
                      </details>

                      {/* Actions */}
                      <div className="flex gap-2 pt-2 border-t">
                        <Button
                          size="sm"
                          variant={task.status === 'approved' ? 'default' : 'outline'}
                          onClick={() => approveTask(task.id)}
                          disabled={task.status === 'approved'}
                          className="flex-1"
                        >
                          <Check className="mr-1 h-3 w-3" />
                          {task.status === 'approved' ? 'Approved' : 'Approve'}
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => rejectTask(task.id)}
                          disabled={task.status === 'rejected'}
                          className="flex-1"
                        >
                          <X className="mr-1 h-3 w-3" />
                          {task.status === 'rejected' ? 'Rejected' : 'Reject'}
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      {/* How it works */}
      <Card>
        <CardHeader>
          <CardTitle>🚀 How It Works (Elon's Way)</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid md:grid-cols-4 gap-4 text-sm">
            <div className="space-y-2">
              <div className="w-10 h-10 rounded-full bg-purple-100 flex items-center justify-center">
                <span className="text-purple-600 font-bold">1</span>
              </div>
              <h4 className="font-semibold">Natural Input</h4>
              <p className="text-muted-foreground text-xs">
                CEO paste danh sách công việc bằng ngôn ngữ tự nhiên
              </p>
            </div>

            <div className="space-y-2">
              <div className="w-10 h-10 rounded-full bg-blue-100 flex items-center justify-center">
                <span className="text-blue-600 font-bold">2</span>
              </div>
              <h4 className="font-semibold">AI Analysis</h4>
              <p className="text-muted-foreground text-xs">
                AI parse, phân loại, match employee tốt nhất + tạo instructions
              </p>
            </div>

            <div className="space-y-2">
              <div className="w-10 h-10 rounded-full bg-green-100 flex items-center justify-center">
                <span className="text-green-600 font-bold">3</span>
              </div>
              <h4 className="font-semibold">CEO Review</h4>
              <p className="text-muted-foreground text-xs">
                Review nhanh, approve/reject tasks. 1-click approve all!
              </p>
            </div>

            <div className="space-y-2">
              <div className="w-10 h-10 rounded-full bg-yellow-100 flex items-center justify-center">
                <span className="text-yellow-600 font-bold">4</span>
              </div>
              <h4 className="font-semibold">Auto-Assign</h4>
              <p className="text-muted-foreground text-xs">
                Tasks tự động giao cho nhân viên với đầy đủ instructions
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
